version: "3.7"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    env_file:
      - .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  memes:
    build: 
      context: ./
      dockerfile: Dockerfile
    # entrypoint: ./script_memes.sh
    command: uvicorn app.memes.main:memes_app --host 0.0.0.0 --port 8000
    volumes:
      - ./memes:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  media:
    build: 
      context: ./
      dockerfile: Dockerfile
      # entrypoint: ./script_media.sh
    command: uvicorn app.media.main:media_app --host 0.0.0.0 --port 8001
    volumes:
      - ./media:/code
    ports:
      - "8001:8001"
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
